server:
  port: 8686
  servlet:
    context-path: /api
spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/rollingFoodsDB?createDatabaseIfNotExist=true"
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    username: "f20161d96baaa6"
    password: "d3d74bc7044d71"
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
static-resources-url: "http://10.0.2.2:8686/images"
storage:
  trucks-image-location: C:\dev\croustify\images\trucks
recaptcha:
  secret-key: "6Lfp22gqAAAAAAAlIY9TgPEhr15d-RehL6tRTQFS"